# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 675dd547fa2d99605be1f4462b52f28e79f444aa9f4f3b3180e15a71a62c4a0b1dc76510b000490eb92f12ccea559497295095b998441fb86406f1d6e5e9323f

test:
  secret_key_base: 972be653c990f8751be8b715272bf80cf91ebfa2f06fd8701b2e5709ae6ab053c5099f345cd80eba84a33868f3926ec8730c550070d331b3d6c0714e39e2b16e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
